### ISSUE TITLE
Add Rise

### ISSUE THREAD

**Issue by dominickm** [simonbru/katy-player#1]
Add rise by Katy Perry ;) 

I use this every day.

**Comment by simonbru** [comment]
Nice :)
I pushed the updated playlist 175f7b25954ed653ac0794cbfe981a252d571312

I don't know if you've seen my PM on reddit by the way. I'll probably add some features in a few days or weeks.

**Comment by dominickm** [comment]
Let me check Reddit and get back to you there!
